---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(quanteda)
library(readtext)
library(topicmodels)
library(tidyverse)
```

```{r}
# Dowload PDF ---------------

pdf_path <- "C:/Users/carol/Desktop/Fall_2020/TADA/Senado/GovProg/programas"

# List PDF
pdfs <- list.files(path = pdf_path, pattern = "*.pdf", full.names = TRUE) 

# Import PDF
spill_texts <- readtext(pdfs,
                        docvarsfrom = "filenames", verbosity = TRUE)

spill_texts
# Corpus
spill_corpus  <- corpus(spill_texts)
spill_corpus$partido <- c("psdb")
summary(spill_corpus)

# DFM

proj_dfm <- dfm(spill_corpus, groups = c("docvar1","partido"),
                remove = stopwords("portugues"),
                remove_numbers = TRUE, 
                remove_punct = TRUE,
                remove_symbols = TRUE,
                verbose  = FALSE, 
                stem = F,
                tolower = TRUE)


proj_dfm <- dfm_select(proj_dfm, min_nchar = 3)
```

## Including Plots

```{r}
# LDA
lda_model <- LDA(proj_dfm, k = 6, control = list(seed = 123))
```

```{r}
#probability of term being generated from topic

topics <- tidy(lda_model, matrix = "beta")

top_terms <- topics %>%
  group_by(topic) %>%
  top_n(10, beta) %>%
  ungroup() %>%
  arrange(topic, -beta) %>% 
  arrange(desc(beta))
top_terms


#graph result -- also in graph.R
top_terms %>%
  mutate(term = reorder_within(term, beta, topic)) %>%
  ggplot(aes(term, beta, fill = factor(topic))) +
  geom_col(show.legend = FALSE) +
  facet_wrap(~ topic, scales = "free") +
  coord_flip() +
  scale_x_reordered()
top_terms
```

```{r doc classification}
#gamma --  XX% of the words in document X that were generated from topic X
gamma <- tidy(lda_model, matrix = "gamma")

#table higher gamma per project
gamma %>% 
  group_by(document) %>% 
  slice_max(gamma, n = 3, with_ties = FALSE) %>% 
  filter(gamma > 0.4) %>% 
  arrange(topic)
```


```{r}
mod1 <- textmodel_wordfish(proj_dfm, dir = c(4, 2))
summary(mod1)
textplot_scale1d(mod1)
```

