---
title: 'Brazilian Senate Speeches'
output: 
  html_document: 
    toc: yes
    theme: paper
    toc_float:
      collapsed: no
    df_print: kable
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r message=FALSE, warning=FALSE}
library(dplyr)
library(ggrepel)
library(ggplot2)
library(tidyverse)
library(tidytext)
library(quanteda)
library(quanteda.textmodels)
library(stm)
```


# Data

```{r}
# Load senators data frame
load("../tada/data/senators.Rda")

# Load speeches data frame
load('../tada/data/sen_df.Rda')
glimpse(sen_df)

# Load corpus
load('../tada/data/sen_corpus.Rda')

# Load DFM
load('../tada/data/sen_dfm.Rda')
```


```{r}
# Additional stopwords
stopwords1 <- c('presidente', 'exa', 'excelencia', 'senhor', 'aqui', 'porque', 'ser',
                'então', 'quero', 'vai', 'ainda', 'ter', 'pode', 'bem', 'obrigado',
                'assim', 'dessa', 'srs', 'cada', 'portanto', 'outro', 'toda', 'além', 
                'nesse', 'nesta', 'desta', 'deste', 'disso', 'sra', 'pois', 'nó', 'sr',
                'aí', 'senador', 'senadores')


# Remove additional stopwords
sen_dfm <- dfm_remove(sen_dfm, stopwords1)

# Set minumum number of characters
sen_dfm <- dfm_select(sen_dfm, min_nchar = 2)

# Keep only words occurring in at most 9/10 of the documents
## acho que não precisa já que a análise vai ser de palavras usadas pelos dois lados. + se usarmos essa função, a palavra 'deus' sai da dfm. ##
#sen_dfm <- dfm_trim(sen_dfm, max_docfreq = 0.95, docfreq_type = 'prop')

# Name documents
docnames(sen_dfm) <- paste(sen_dfm$Partido)

# Summary 
head(dfm_sort(sen_dfm, decreasing = TRUE, margin = 'both'), n = 10, nf = 5) 
```


# Number of senators/speeches by gender/state

```{r message=FALSE, warning=FALSE}
# Table
senators %>% 
  group_by(party_abbr, gender) %>% 
  summarise(n = n())

# Plot senators by gender
gender_sen <- senators %>% 
  group_by(party_abbr, gender) %>% 
  summarise(n = n()) %>%
  ggplot(aes(party_abbr, n)) +
  geom_col(aes(fill = gender)) +
  ylab("# Senators") +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 90)) 

# Plot speeches by gender
gender_speech <- sen_df %>% 
  group_by(Partido, gender) %>% 
  summarise(n = n()) %>%
  ggplot(aes(Partido, n)) +
  geom_col(aes(fill = gender)) +
  ylab("# Speeches") +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 90))

gridExtra::grid.arrange(gender_sen, gender_speech)


# Plot senators by state
state_sen <- senators %>% 
  group_by(state, gender) %>% 
  summarise(n = n()) %>%
  ggplot(aes(state, n)) +
  geom_col(aes(fill = gender)) +
  ylab("# Senators") +
  theme_classic() 

# Plot speeches by state
state_speech <- sen_df %>% 
  group_by(UfParlamentarNaData, gender) %>% 
  summarise(n = n()) %>%
  ggplot(aes(UfParlamentarNaData, n)) +
  geom_col(aes(fill = gender)) +
  ylab("# Speeches") +
  theme_classic() 

gridExtra::grid.arrange(state_sen, state_speech)
```


# Keyness 

```{r}
textplot_keyness(textstat_keyness(sen_dfm, target = sen_dfm$Partido == "PSL"))
textplot_keyness(textstat_keyness(sen_dfm, target = sen_dfm$Partido == "PT"))
textplot_keyness(textstat_keyness(sen_dfm, target = sen_dfm$Partido == "PSDB"))
```


# Wordfish

```{r}
# Print doc 20
sen_dfm[20,1]

# Print doc 19
sen_dfm[19,1]

# Wordfish model
wf <- textmodel_wordfish(sen_dfm, dir = c(20, 19), sparse = TRUE)
```

## Party Position

```{r}
# Graph party positions
textplot_scale1d(wf)
```

```{r}
# Table with party position from external sources
load("../tada/data/wiki_partidos.Rda")
wiki_partidos
```


## Feature Analysis

```{r}
# Graph word positions
textplot_scale1d(wf, margin = 'features', highlighted = 'deus', 'religião')

# Features usage left/right
feat <- data.frame(
  word = wf$features,
  beta = wf$beta,
  psi = wf$psi,
  stringsAsFactors = FALSE)

# Graph top 30 psi per beta
feat %>% 
  top_n(30, psi) %>%  # word fixed-effects
  ggplot(aes(x = beta, y = psi, label = word)) +
  geom_point() +
  geom_text_repel() +
  theme_classic()

# Left
feat %>% 
  top_n(-30, beta)

# Right
feat %>% 
  top_n(30, beta)
```


# Religion

## Word Collocations

```{r}
# Keyword in context == 'evangélico'
kwic(sen_corpus, pattern = 'evangélico', window = 3, valuetype = 'glob')
```


## Word Correlations

```{r message=FALSE, warning=FALSE}
# Convert dfm into relative frequency and find correlations
dfm_weight(sen_dfm, scheme = "prop") %>% 
    textstat_simil(selection = c("deus", "evangélico", "igreja"), 
                   method = "correlation", margin = "features") %>%
    as.matrix() %>%
    head(15)
```



